# Generated by Django 4.1.3 on 2023-05-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr_management', '0006_remove_employee_user_employee_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.CharField(choices=[('manager', 'Manager'), ('waiter', 'Waiter'), ('chef', 'Chef'), ('cleaner', 'Cleaner')], max_length=20),
        ),
    ]
